permalink: /:title

url:
baseurl:

markdown: redcarpet
redcarpet:
  extensions: [strikethrough, tables, autolink]
highlighter: pygments

sass:
  sass_dir: public/css
  style: :compressed
  
gems:
  - jekyll-redirect-from #https://help.github.com/articles/redirects-on-github-pages
  - jekyll-mentions
  
social:
  email: mailto:contact@programminglife.io
  github: http://github.com/andreivisan
  linkedin: https://www.linkedin.com/company-beta/17906021/
  twitter: https://twitter.com/Programminglife.io
  stackoverflow: http://stackoverflow.com/users/3426717/andrei
  googleplus: https://plus.google.com/115682876566536754762
  instagram: https://www.instagram.com/programminglife.io/
