permalink: /:title

url:
baseurl:

markdown: redcarpet
redcarpet:
  extensions: [strikethrough, tables, autolink]
highlighter: pygments

sass:
  sass_dir: public/css
  style: :compressed
  
gems:
  - jekyll-redirect-from #https://help.github.com/articles/redirects-on-github-pages
  - jekyll-mentions
  
social:
  email: mailto:andrei.m.visan@gmail.com
  github: http://github.com/andreivisan
  linkedin: http://linkedin.com/in/andreivisan
  twitter: https://twitter.com/andreivisan
  stackoverflow: http://stackoverflow.com/users/3426717/andrei
